"use effect";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import { TransactionContextProvider } from "@/lib/providers/transaction-context-provider";
import AppStateProvider from "@/lib/providers/state-provider";
import { Analytics } from "@vercel/analytics/react"
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark" //or system probably, seems more stable
            enableSystem
            disableTransitionOnChange
          >

            <TransactionContextProvider>
              <AppStateProvider>
                {children}
                <Analytics />
                <Toaster/>
              </AppStateProvider>
            </TransactionContextProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
